[package]
name = "drs"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
drsplayer = { path = "../drs-player" }
hlua51 = { git = "https://github.com/rkusa/hlua51.git" }
lua51-sys = { git = "https://github.com/rkusa/hlua51.git" }
libc = "0.2"
log = "0.4"
log4rs = "0.8"
const-cstr = "0.1"